### ISSUE TITLE
BLE Incorrect MTU

### ISSUE THREAD

**Issue by tomaszduda23** [intercreate/smpclient#21]
I've tested version 2.0.1 a few more times. It looks that MTU is calculated incorrectly sometimes. The log after a few runs look like:
```bash
INFO smp_characteristic.max_write_without_response_size=20
INFO smp_characteristic.max_write_without_response_size=495
```
It seems that this should be still added
```c++
        # BlueZ doesn't have a proper way to get the MTU, so we have this hack.
        # If this doesn't work for you, you can set the client._mtu_size attribute
        # to override the value instead.
        if self._client._backend.__class__.__name__ == "BleakClientBlueZDBus":
            await self._client._backend._acquire_mtu()
```

**Comment by JPHutchins** [comment]
There is a Windows-specific workaround, but it looks like it may be required for Linux as well... either way, I'd like to hear more from Bleak about the "best way".

https://github.com/intercreate/smpclient/blob/0f47207c8d44b843a599d23ff7dd202dcdac25c2/smpclient/transport/ble.py#L73-L85

**Comment by JPHutchins** [comment]
Hmmm, BlueZ gets it here: https://github.com/hbldh/bleak/blob/b8149a5b5504eaacbd45ee56c1339fa4395e1345/bleak/backends/bluezdbus/manager.py#L697-L699

**Comment by tomaszduda23** [comment]
Right now it defaults to 20 %50 of times. Calling this explicit works 100% time https://github.com/tomaszduda23/smpclient/blob/d25c8035ae2858fd41a106058297b619d58fbcb5/smpclient/transport/ble.py#L84
It seems that there is a race in bleak. Perhaps value is set only once and sometimes it happens before MTU negotiation is completed.
Could you consider adding this code temporary? It is main blocker for me know.

**Comment by JPHutchins** [comment]
@tomaszduda23 Agreed that we need the fix now, I will add it back!

I’ll be advocating for Bleak to add acquire_mtu() to the public interface.

**Comment by tomaszduda23** [comment]
I've tested 3.0.1 and MTU works correctly :+1:
