### ISSUE TITLE
add timeout for SMPClient.upload

### ISSUE THREAD

**Issue by tomaszduda23** [intercreate/smpclient#26]
It happens that during transfer something go wrong. It would be nice to have possibility to set:
1. timeout for each chunk
2. different timeout for first chunk since it may required be bigger than the others

```python
async for offset in smp_client.upload(image):
    progress.update(offset / upload_size)
```
For other function timeout can be set outside.
```python
await asyncio.wait_for(
        smp_client.request(ImageStatesWrite(hash=image_tlv_sha256)),
        timeout=1.0,
    )
```

**Comment by JPHutchins** [comment]
Do you recommend adding defaults to the upload method?  What would be good defaults?

```python
async def upload(
    self,
    image: bytes, slot: int = 0,
    upgrade: bool = False,
    first_packet_timeout_s: int = 30,
    packet_timeout_s: int = 1
) -> AsyncIterator[int]:
```

> For other function timeout can be set outside.

Do you think this is OK?  The reason that there are no timeouts on requests is that I don't want to take flexibility away from users.  They can use asyncio.timeout or asyncio.wait_for as you showed.  That said, maybe I should add a default timeout to request that's 120 seconds - unlikely to cause problems if some one is not expecting the timeout.  IDK!

**Comment by tomaszduda23** [comment]
go implementation use following values for default timeouts 
    FIRST_TIMEOUT = 40.000sec
    TIMEOUT = 2.500sec

> I should add a default timeout to request that's 120 seconds

BLE upload is not supper reliable for some reason. It failes 30% of time. It is not big problem since it resumes from the last offset. Waiting 2 min to repeat is a lot...
That is why I would prefer to have 2 different values of timeout.

**Comment by tomaszduda23** [comment]
I just figure out that it can be done outside too. Not too pretty but works.
```python
            iter = (smp_client.upload(image))
            iter = type(iter).__aiter__(iter)
            running = True
            timeout = 40.0

            while running:
                try:
                    offset = await asyncio.wait_for(type(iter).__anext__(iter), timeout)
                    progress.update(offset / upload_size)
                    timeout = 2.5
                except StopAsyncIteration:
                    running = False
                except asyncio.exceptions.TimeoutError:
                    _LOGGER.warning("Upload timeout.")
                    return 1
```

**Comment by JPHutchins** [comment]
Nice!  But I will add the MCUmgr defaults to prevent the ugliness!

**Comment by tomaszduda23** [comment]
I already take care for this on client side.
```python
async def smpmgr_upload(config, host, firmware):
    for attempt in range(3):
        try:
            return await smpmgr_upload_(config, host, firmware)
        except SMPBLETransportDeviceNotFound:
            if attempt == 2:
                raise
```
It is possible to debug but not very high on my TODO list. BLE serial also drops data. Most likely there is some issue in BLE stack.
