### ISSUE TITLE
Swap does not happen when I test an image [BLE]

### ISSUE THREAD

**Issue by vChavezB** [intercreate/smpclient#60]
If I do a confirm, the swap starts without a problem

```python
client.request(ImageStatesWrite(hash=image.hash,confirm=True))
```

however when I do not confirm the image (i.e., test), the swap does not start

```python
client.request(ImageStatesWrite(hash=image.hash,confirm=False))
```

Here is the log when I do confirm
```
[00:01:50.219,421] <dbg> mcumgr_img_grp: img_mgmt_get_next_boot_slot: (0, *) => slot = 0, type = 0
[00:01:50.219,451] <dbg> mcumgr_img_grp: img_mgmt_set_next_boot_slot: (1, confirm)
[00:01:50.219,482] <dbg> mcumgr_img_grp: img_mgmt_set_next_boot_slot: aimg = 0, img = 0, aslot = 0, slot = 1, nbs = 0
[00:01:50.221,649] <dbg> mcuboot_util: boot_write_magic: writing magic; fa_id=2 off=0x6bff0 (0x6bff0)
[00:01:50.230,926] <dbg> mcuboot_util: boot_write_image_ok: writing image_ok; fa_id=2 off=0x6bfe8 (0x6bfe8)
[00:01:50.240,142] <dbg> mcuboot_util: boot_write_swap_info: writing swap_info; fa_id=2 off=0x6bfd8 (0x6bfd8), swap_type=0x3 image_num=0x0
*** Booting MCUboot fb2cf0ec3da3 ***
*** Using Zephyr OS build 36940db938a8 ***
[00:00:00.001,312] <inf> mcuboot: Starting bootloader
[00:00:00.002,899] <inf> mcuboot: mcuboot status 0
[00:00:00.003,753] <inf> mcuboot: Primary image: magic=good, swap_type=0x3, copy_done=0x1, image_ok=0x1
[00:00:00.004,486] <inf> mcuboot: Secondary image: magic=good, swap_type=0x3, copy_done=0x2, image_ok=0x1
[00:00:00.004,913] <inf> mcuboot: Boot source: none
[00:00:00.005,645] <inf> mcuboot: Image index: 0, Swap type: perm
[00:00:01.954,406] <inf> mcuboot: mcuboot status 1
[00:00:01.955,993] <inf> mcuboot: Starting swap using move algorithm.
[00:00:47.384,338] <inf> mcuboot: Bootloader chainload address offset: 0x14000
[00:00:47.384,674] <inf> mcuboot: Jumping to the first image slot
```

and here when I do a test 

```
[00:03:41.361,114] <dbg> mcumgr_img_grp: img_mgmt_get_next_boot_slot: (0, *) => slot = 0, type = 0
[00:03:41.361,145] <dbg> mcumgr_img_grp: img_mgmt_set_next_boot_slot: (1, test)
[00:03:41.361,175] <dbg> mcumgr_img_grp: img_mgmt_set_next_boot_slot: aimg = 0, img = 0, aslot = 0, slot = 1, nbs = 0
[00:03:41.363,342] <dbg> mcuboot_util: boot_write_magic: writing magic; fa_id=2 off=0x6bff0 (0x6bff0)
*** Booting MCUboot fb2cf0ec3da3 ***
*** Using Zephyr OS build 36940db938a8 ***
[00:00:00.001,312] <inf> mcuboot: Starting bootloader
[00:00:00.002,899] <inf> mcuboot: mcuboot status 0
[00:00:00.003,753] <inf> mcuboot: Primary image: magic=good, swap_type=0x3, copy_done=0x1, image_ok=0x1
[00:00:00.004,486] <inf> mcuboot: Secondary image: magic=good, swap_type=0x2, copy_done=0x2, image_ok=0x2
[00:00:00.005,493] <inf> mcuboot: Boot source: none
[00:00:00.006,256] <inf> mcuboot: Image index: 0, Swap type: none
```

Perhaps I am missing a config in mcumgr?, From the logs I understand that the image_ok is being set to [BOOT_FLAG_BAD]( https://github.com/zephyrproject-rtos/mcuboot/blob/f5454f16358225f69ff729301c8e56d8a580f81a/boot/bootutil/include/bootutil/bootutil_public.h#L110), hence the swap does not occur.

I will update the issue if I find something missing on my side.

**Comment by JPHutchins** [comment]
It doesn't look like you're doing anything different than the existing HW integration test: https://github.com/intercreate/smpclient/blob/main/examples/ble/upgrade.py

It only marks for test. Pre-confirming the image can brick the device, so let's figure this out.

**Comment by vChavezB** [comment]
Yes exactly, I am using the `ImageStatesWrite` request, and marking for test. This is seen in the log. However I noticed that when the reboot occurs I get `Swap type: none`, instead of `Swap type: test` which is what should [trigger](https://github.com/zephyrproject-rtos/mcuboot/blob/f5454f16358225f69ff729301c8e56d8a580f81a/boot/bootutil/src/loader.c#L2234) the swap.

**Comment by vChavezB** [comment]
This is what I get after the `ImageStatesWrite` request

```
slot=0  bootable=True pending=False confirmed=True active=True permanent=False
slot=1 bootable=True pending=False confirmed=False active=False permanent=False
```

**Comment by JPHutchins** [comment]
I don't know the MCUBoot enums offhand, but I can say that pending should be true after the image state write.

**Comment by vChavezB** [comment]
Thanks for the info. I will check why the image is not pending.

**Comment by JPHutchins** [comment]
I wonder if it's related to minimum write size? MCUBoot must rely on the minimum writable size if it's updating header or trailer in flash.

**Comment by vChavezB** [comment]
I think this might be what is happening. Do you know if there is a KConfig to set it ?

**Comment by JPHutchins** [comment]
It would make sense for it to use the flash driver's parameters, but we'd have to check source to verify.

What platform are you using, if you can say?

**Comment by vChavezB** [comment]
NRF52833, but the flash for slot 1 is an external custom SPI Flash.

**Comment by JPHutchins** [comment]
Cool, we have a custom board using 52840 and external SPI flash for slot 1. What flash and what flash driver?

**Comment by vChavezB** [comment]
Its a renesas AT25pe80. It does not support the JEDE commands so I have a custom driver. The minimum write of a page is 256. What I see that is happening is that mcuboot writes to the trailer with size 1, and hence deletes the other flags (image_ok)

**Comment by JPHutchins** [comment]
It's AT25 but not compatible with the the spi_nor driver? https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/flash/spi_nor.c

The flash seems to have JEDEC ID. Maybe it doesn't have "JESD216" and "SFDP" and it does kinda look like those are required for the spi nor driver: https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/flash/Kconfig.nor

Would be good to investigate how the smp server / MCUboot deal with minimum write size limitations.

**Comment by vChavezB** [comment]
Yes, its not compatible. When I integrated the flash in my project i could not use the driver out of the box. 

Update:

I have modified my driver and internally read the flash page if the write size is less than the page size. This avoids overwriting the other trailer fields. And now after the Image write, the test image is swapped 👍  

Yes I agree it would make more sense to investigate the minimum write size. This is were I see that the write of size 1 happens

https://github.com/vChavezB/mcuboot/blob/d4394c2f9b76e0a7b758441cea3a8ceb896f66c8/boot/bootutil/src/bootutil_public.c#L393

**Comment by JPHutchins** [comment]
> Yes, its not compatible. When I integrated the flash in my project i could not use the driver out of the box.
> 
> Update:
> 
> I have modified my driver to support partial writes. This avoids overwriting the other trailer fields. And now after the Image write request with smpclient, the test image is swapped 👍
> 
> Yes I agree it would make more sense to investigate the minimum write size. This is were I see that the write of size 1 happens
> 
> https://github.com/zephyrproject-rtos/mcuboot/blob/f5454f16358225f69ff729301c8e56d8a580f81a/boot/bootutil/src/bootutil_public.c#L393

Nice! Good find on the 1 byte write... it's fine as long as that 1 byte write is at the beginning of an aligned region of "minimum write size", correct? E.g., for STM32 internal flash that has minimum write size of 8 bytes, even though the swap info only occupies 1 byte, it would be padded out to 8 so that it's possible to erase and write again (in this example it's assumed that the flash can only write if all 8 bytes are first erased to 0xFF).

**Comment by vChavezB** [comment]
I think that as long as the flash driver supports partial writes or the flash minum write size is of size <=8 it works. 

I see that mcuboot gets the maximum alignment [here](
https://github.com/zephyrproject-rtos/mcuboot/blob/f5454f16358225f69ff729301c8e56d8a580f81a/boot/zephyr/include/mcuboot_config/mcuboot_config.h#L331),  which is dependent on the `block-write-size` property of `zephyr,flash` in device tree .

Mcuboot [checks](https://github.com/zephyrproject-rtos/mcuboot/blob/f5454f16358225f69ff729301c8e56d8a580f81a/boot/bootutil/src/bootutil_public.c#L332) that the write [alignment](https://github.com/zephyrproject-rtos/mcuboot/blob/f5454f16358225f69ff729301c8e56d8a580f81a/boot/bootutil/src/bootutil_public.c#L330) of the flash where the trailer will be written is not greater than the `block-write-size` of `zephyr,flash`. 

In my case I defined it as 1 byte, so it happily writes to 1 byte of flash. However, if I want to enforce it to 256 bytes then the `boot_write_trailer` will return an error.
